function mom_array = select_moments(m)
% Returns array of moments to fit given a structure 'm' with all
% computed moments.

mom_array = [...
    m.up,...
    m.us,...
    m.sp,...
    m.ps,...
    m.pu_1,...
    m.pu_2,...
    m.pu_3,...
    m.pu_4,...
    m.su_1,...
    m.su_2,...
    m.su_3,...
    m.su_4,...
    m.lnern_avg_2_1,... 
    m.lnern_avg_3_1,... 
    m.lnern_avg_2_2,... 
    m.lnern_avg_3_2,... 
    m.lnern_avg_2_3,... 
    m.lnern_avg_3_3,... 
    m.lnern_avg_2_4,...
    m.lnern_avg_3_4,...
    m.lnern_std_2,...
    m.lnern_std_3,...
    m.lnern_rho_2,...
    m.lnern_rho_3,...
    m.dlnern_p50_ps,...
    m.dlnern_p50_sp,...
    m.nlw_share_leq0_1,...
    m.nlw_share_leq0_2,...
    m.nlw_share_leq0_3,...
    m.nlw_p75_ecdf_1,...
    m.nlw_p75_ecdf_2,...
    m.nlw_p75_ecdf_3,...
];


