function pn_all = stack_panels(pn)
% Stack panels for each worker cluster.

% Note. Number of clusters is hardcoded,  but could be easily fixed
% retrieving number of individuals simulated in  each panel, p.N

pn_all.lfs = [pn{1}.lfs;pn{2}.lfs;pn{3}.lfs;pn{4}.lfs];
pn_all.nlw = [pn{1}.nlw;pn{2}.nlw;pn{3}.nlw;pn{4}.nlw];
pn_all.ern = [pn{1}.ern;pn{2}.ern;pn{3}.ern;pn{4}.ern];

pn_all.spell_num = [...
    pn{1}.spell_num;...
    pn{2}.spell_num;...
    pn{3}.spell_num;...
    pn{4}.spell_num;...
    ];

pn_all.spell_dur = [...
    pn{1}.spell_dur;...
    pn{2}.spell_dur;...
    pn{3}.spell_dur;...
    pn{4}.spell_dur;...
    ];

pn_all.spell_lnern = [...
    pn{1}.spell_lnern;...
    pn{2}.spell_lnern;...
    pn{3}.spell_lnern;...
    pn{4}.spell_lnern;...
    ];

pn_all.cluster_id = [...
    pn{1}.cluster_id;...
    pn{2}.cluster_id;...
    pn{3}.cluster_id;...
    pn{4}.cluster_id;...
    ];
